### ISSUE TITLE
Float deprecation warnings

### ISSUE THREAD

**Issue by norm2782** [timjb/quantities#3]
Type checking ./Quantities/Power.idr
./Quantities/Power.idr:57:10:Use of deprecated name Float
./Quantities/Power.idr:57:10:Use of deprecated name Float
./Quantities/Power.idr:57:10:Use of deprecated name Float
./Quantities/Power.idr:58:9:Use of deprecated name Float
./Quantities/Power.idr:58:9:Use of deprecated name Float
./Quantities/Power.idr:58:9:Use of deprecated name Float
./Quantities/Power.idr:58:9:Use of deprecated name Float
./Quantities/Power.idr:59:9:Use of deprecated name Float
./Quantities/Power.idr:59:9:Use of deprecated name Float
./Quantities/Power.idr:59:9:Use of deprecated name Float
./Quantities/Power.idr:60:5-7:Use of deprecated name Float
./Quantities/Power.idr:60:5-7:Use of deprecated name Float
./Quantities/Power.idr:60:5-7:Use of deprecated name Float
./Quantities/Power.idr:60:5-7:Use of deprecated name Float
./Quantities/Power.idr:59:38:Use of deprecated name Float
./Quantities/Power.idr:59:38:Use of deprecated name Float
./Quantities/Power.idr:59:38:Use of deprecated name Float
./Quantities/Power.idr:59:38:Use of deprecated name Float
./Quantities/Power.idr:59:9:Use of deprecated name Float
./Quantities/Power.idr:59:9:Use of deprecated name Float
Type checking ./Quantities/FreeAbelianGroup.idr
Type checking ./Quantities/Core.idr
./Quantities/Core.idr:52:8:Use of deprecated name Float
./Quantities/Core.idr:52:8:Use of deprecated name Float
./Quantities/Core.idr:52:8:Use of deprecated name Float
./Quantities/Core.idr:52:8:Use of deprecated name Float
./Quantities/Core.idr:52:8:Use of deprecated name Float
./Quantities/Core.idr:52:8:Use of deprecated name Float
./Quantities/Core.idr:52:8:Use of deprecated name Float
./Quantities/Core.idr:52:8:Use of deprecated name Float
./Quantities/Core.idr:52:8:Use of deprecated name Float
./Quantities/Core.idr:52:8:Use of deprecated name Float
./Quantities/Core.idr:78:17:Use of deprecated name Float
./Quantities/Core.idr:78:17:Use of deprecated name Float
./Quantities/Core.idr:79:17:Use of deprecated name Float
./Quantities/Core.idr:79:17:Use of deprecated name Float
./Quantities/Core.idr:133:22:Use of deprecated name Float
./Quantities/Core.idr:133:22:Use of deprecated name Float
./Quantities/Core.idr:134:22:Use of deprecated name Float
./Quantities/Core.idr:139:20:Use of deprecated name Float
./Quantities/Core.idr:139:20:Use of deprecated name Float
./Quantities/Core.idr:140:20:Use of deprecated name Float
./Quantities/Core.idr:140:20:Use of deprecated name Float
./Quantities/Core.idr:140:20:Use of deprecated name Float
./Quantities/Core.idr:140:20:Use of deprecated name Float
./Quantities/Core.idr:285:3:Use of deprecated name Float
./Quantities/Core.idr:321:18:Use of deprecated name Float
./Quantities/Core.idr:322:18:Use of deprecated name Float
Type checking ./Quantities/SIPrefixes.idr
Type checking ./Quantities/SIBaseQuantities.idr
Type checking ./Quantities/SIBaseUnits.idr
Type checking ./Quantities/SIDerivedQuantities.idr
Type checking ./Quantities/SIDerivedUnits.idr
Type checking ./Quantities.idr
Type checking ./Quantities/NonSIUnits.idr
./Quantities/NonSIUnits.idr:17:8:Use of deprecated name Float
./Quantities/NonSIUnits.idr:22:6:Use of deprecated name Float
./Quantities/NonSIUnits.idr:27:5:Use of deprecated name Float
./Quantities/NonSIUnits.idr:32:6:Use of deprecated name Float
./Quantities/NonSIUnits.idr:49:7:Use of deprecated name Float
./Quantities/NonSIUnits.idr:69:18:Use of deprecated name Float
./Quantities/NonSIUnits.idr:92:5:Use of deprecated name Float
./Quantities/NonSIUnits.idr:95:9:Use of deprecated name Float
./Quantities/NonSIUnits.idr:100:6:Use of deprecated name Float
./Quantities/NonSIUnits.idr:105:7:Use of deprecated name Float
./Quantities/NonSIUnits.idr:112:5:Use of deprecated name Float
./Quantities/NonSIUnits.idr:182:18:Use of deprecated name Float
./Quantities/NonSIUnits.idr:187:14:Use of deprecated name Float
./Quantities/NonSIUnits.idr:192:19:Use of deprecated name Float
./Quantities/NonSIUnits.idr:197:13:Use of deprecated name Float
./Quantities/NonSIUnits.idr:202:13:Use of deprecated name Float
./Quantities/NonSIUnits.idr:207:11:Use of deprecated name Float
./Quantities/NonSIUnits.idr:212:10:Use of deprecated name Float
./Quantities/NonSIUnits.idr:217:11:Use of deprecated name Float
./Quantities/NonSIUnits.idr:222:11:Use of deprecated name Float
Type checking ./Quantities/ImperialUnits.idr
./Quantities/ImperialUnits.idr:30:6:Use of deprecated name Float
./Quantities/ImperialUnits.idr:35:6:Use of deprecated name Float
./Quantities/ImperialUnits.idr:40:7:Use of deprecated name Float
./Quantities/ImperialUnits.idr:45:9:Use of deprecated name Float
./Quantities/ImperialUnits.idr:50:6:Use of deprecated name Float
./Quantities/ImperialUnits.idr:55:8:Use of deprecated name Float
./Quantities/ImperialUnits.idr:67:7:Use of deprecated name Float
./Quantities/ImperialUnits.idr:70:14:
Use of deprecated name Float
./Quantities/ImperialUnits.idr:86:6:Use of deprecated name Float
./Quantities/ImperialUnits.idr:94:7:Use of deprecated name Float
./Quantities/ImperialUnits.idr:97:6:Use of deprecated name Float
./Quantities/ImperialUnits.idr:100:6:
Use of deprecated name Float
./Quantities/ImperialUnits.idr:111:6:
Use of deprecated name Float
./Quantities/ImperialUnits.idr:116:6:
Use of deprecated name Float
./Quantities/ImperialUnits.idr:121:7:
Use of deprecated name Float
./Quantities/ImperialUnits.idr:126:8:
Use of deprecated name Float
./Quantities/ImperialUnits.idr:138:14:
Use of deprecated name Float
./Quantities/ImperialUnits.idr:143:13:
Use of deprecated name Float
./Quantities/ImperialUnits.idr:171:7:
Use of deprecated name Float
./Quantities/ImperialUnits.idr:176:9:
Use of deprecated name Float
./Quantities/ImperialUnits.idr:181:15:
Use of deprecated name Float
./Quantities/ImperialUnits.idr:186:5:
Use of deprecated name Float
./Quantities/ImperialUnits.idr:192:11:
Use of deprecated name Float
./Quantities/ImperialUnits.idr:200:22:
Use of deprecated name Float
Type checking ./Quantities/Information.idr
./Quantities/Information.idr:12:6:Use of deprecated name Float
./Quantities/Information.idr:19:13:Use of deprecated name Float
Type checking ./Quantities/Screen.idr
./Quantities/Screen.idr:25:20:Use of deprecated name Float
./Quantities/Screen.idr:32:14:Use of deprecated name Float

**Comment by norm2782** [comment]
With latest git revision of Idris. Float should be Double.

**Comment by timjb** [comment]
Thanks for reporting this!
