### ISSUE TITLE
Doesn't compile on Idris 1.0

### ISSUE THREAD

**Issue by NOTtheMessiah** [timjb/quantities#8]
In _Core.idr_, the dependent function `ElemUnit'` doesn't seem to count as a type constructor. Attempting to compile gives

    ./Quantities/Core.idr line 65 col 15:
    (q : FreeAbGrp Dimension ** ElemUnit q)  cannot be a parameter of Prelude.Interfaces.Eq
    (Implementation arguments must be type or data constructors)

I suspect this issue is related to https://github.com/idris-lang/Idris-dev/issues/3727

**Comment by timjb** [comment]
Fixed by 087fcbda0a70265588f3048eff8937f6a00d6e93.
